services:
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - DB_HOST=db
      - DB_NAME=embeddings_db
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_PORT=5432
      - PORT=5000
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: ankane/pgvector:latest
    environment:
      - POSTGRES_DB=embeddings_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data: